name: Stok Robotu Otomasyonu

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-ve-rapor:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/playwright/python:v1.58.0-jammy
      options: --user 1001

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Kütüphaneleri Yükle
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Robotu Çalıştır
        run: |
          python -m pytest tests/test_stok_ekle.py --alluredir=allure-results

      - name: Raporu Oluştur
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          subfolder: allure-report

      - name: Raporu Yayınla
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: allure-report

  deploy:
    name: Web Sitesini Yayınla
    needs: test-ve-rapor
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages'e Deploy
        id: deployment
        uses: actions/deploy-pages@v4
