name: Stok Robotu Otomasyonu

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-ve-rapor:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/playwright/python:v1.58.0-jammy
      options: --user 1001

    steps:
      - name: KodlarÄ± Ã‡ek
        uses: actions/checkout@v4

      - name: KÃ¼tÃ¼phaneleri YÃ¼kle
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Robotu Ã‡alÄ±ÅŸtÄ±r
        env: # EKSÄ°K OLAN VE EKLENEN KISIM BURASI ðŸ‘‡
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASS: ${{ secrets.USER_PASS }}
          FIRM_CODE: ${{ secrets.FIRM_CODE }}
        run: |
          python -m pytest tests/test_stok_ekle.py --alluredir=allure-results

      - name: Raporu OluÅŸtur
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          subfolder: allure-report

      - name: Raporu YayÄ±nla
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: allure-report

  deploy:
    name: Web Sitesini YayÄ±nla
    needs: test-ve-rapor
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages'e Deploy
        id: deployment
        uses: actions/deploy-pages@v4
